### ISSUE TITLE
[worker reload] [worker init] Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'e:

### ISSUE THREAD

**Issue by Spimy** [dword-design/nuxt-mail#146] opened 2023-02-16 17:04 UTC
I keep getting the error mentioned in the title no matter what config I provide.
This is what I have in my `nuxt.config.ts`:
```ts
  modules: [
    '@nuxtjs/color-mode',
    [
      'nuxt-mail',
      {
        message: [{ name: 'contact', to: process.env.EMAIL }],
        smtp: {
          host: 'smtp.office365.com',
          secureConnection: false,
          port: 587,
          auth: {
            user: process.env.EMAIL,
            pass: process.env.EMAIL_PASSWORD
          }
        }
      }
    ]
  ],
```

**Comment by tidan-16** [comment] 2023-02-21 23:20
Same issue here

**Comment by dword-design** [comment] 2023-02-22 10:29
Duplicate of https://github.com/dword-design/nuxt-mail/issues/143

**Closed by dword-design** 2023-02-22 10:29 UTC
